### ISSUE TITLE
Out of memory exception on Android

### ISSUE THREAD

**Issue by duydao** [nolanlawson/cordova-plugin-sqlite-2#45]
Thanks for this plugin, we really appreciate it!

I'm getting an out of memory exception when trying to store a 14MB JSON into the database:

Throwing OutOfMemoryError "Failed to allocate a 41535454 byte allocation with 16777216 free bytes and 28MB until OOM

The same JSON loads fine on an iPhone.

```
at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:146)
at java.lang.StringBuilder.append(StringBuilder.java:216)
at com.nolanlawson.cordova.sqlite.SQLitePlugin.appendPluginResult(SQLitePlugin.java:256)
at com.nolanlawson.cordova.sqlite.SQLitePlugin.pluginResultsToString(SQLitePlugin.java:213)
at com.nolanlawson.cordova.sqlite.SQLitePlugin.runInBackground(SQLitePlugin.java:67)
at com.nolanlawson.cordova.sqlite.SQLitePlugin.access$000(SQLitePlugin.java:24)
at com.nolanlawson.cordova.sqlite.SQLitePlugin$1.run(SQLitePlugin.java:56)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by nolanlawson** [comment]
It's probably just too large of an object to store in SQLite. Note that Cordova has a limitation where all data has to be serialized into strings when sent between the WebView and the native context.

You may want to look into WebSQL or IndexedDB, or break up your JSON object into smaller pieces.

**Comment by nolanlawson** [comment]
Also the reason it fails in Android but not iOS is probably just due to device differences

**Comment by danielehrhardt** [comment]
Is there a new fix?

**Comment by ganeshmogare** [comment]
@nolanlawson  can you put some more light on **"or break up your JSON object into smaller pieces"**
